# Site settings
title: Max Zvyagin
description: My personal webpage.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: maxzvyagin.github.io

# User settings
username: Max Zvyagin
user_description:
user_title: Predoctoral Appointee
email: max.zvyagin7@gmail.com
#twitter_username: lorem_ipsum
github_username:  maxzvyagin
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
